### PR TITLE
Python 3 ready (non-ascii ok!)

### PR DESCRIPTION
**Pull request by ebrensi**
Activities containing text with characters like ö, ä, ü are written correctly to activity files and the summary csv.  This script is fully Python 2/3 compatible and PEP8 compliant. 

This update of gcexport.py uses requests module, and logging module instead of print statements.  Otherwise, some general workflow clean-up.  Aside from being Python 3 compatible and handling non-ascii characters, this script functions identically.  

I also included fixes for issues https://github.com/kjkjava/garmin-connect-export/issues/10 and https://github.com/kjkjava/garmin-connect-export/issues/11.

### CODE REVIEW

**Comment by travsgweber** [comment]
Hi!   Have you confirmed that these versions are Python 3 compatible?   I just spent the day getting the original code set to run in Python 3.  The print statements were one thing, but the variance between string and binary variables was another.    This set of code here looks a bit cleaner, so maybe I'll go through and make my Python 3 changes here?

**Comment by ebrensi** [comment]
Yes, I just now ran it with python 3.5 on my (Linux Mint) laptop.   I went through a bit of trial and error to get string encoding right.  Mine has the added benefit that it can handle non-ascii characters in the activity name and description, which is an issue for European users.    

btw I ended up adapting your script to populate a PostgreSQL database here:
https://github.com/ebrensi/running_data/blob/master/gcexport-db.py
which I'm using for a little activity tracker app.

**Comment by travsgweber** [comment]
Thanks, I’m not the original author though.   I’m just modifying it as well to my own purposes.       That’s cool what you did though, I also want to export it and import it into an Amazon Web Services mysql server.      Your PostgreSQL code looks like it may work with a bit of modification.

t.

**Comment by travsgweber** [comment]
Sorry guys, just noticed I was cc’d on the thread (not direct recipient).

My bad   ;-)

Trav.

**Comment by travsgweber** [comment]
Your heatmap is pretty cool.

Trav.

**Comment by ebrensi** [comment]
Well this pull request is no longer relevant.

**Pull request closed without merging**
